import type { Config } from 'tailwindcss';

/**
 * Golf Sol — design system: premium, clean, Costa del Sol / Irish golfers.
 * Primary = dark green (trust, golf). Accent = warm orange (CTAs that pop).
 */
const config: Config = {
  darkMode: ['selector', '[data-theme="dark"]'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        /* Theme tokens (theme.css :root / [data-theme="dark"]) */
        bg: 'var(--color-bg)',
        surface: 'var(--color-surface)',
        'surface-raised': 'var(--color-surface-raised)',
        'surface-overlay': 'var(--color-surface-overlay)',
        'surface-alt': 'var(--color-surface-alt)',
        text: 'var(--color-text)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        border: 'var(--color-border)',
        'border-subtle': 'var(--color-border-subtle)',
        'border-strong': 'var(--color-border-strong)',
        'focus-ring': 'var(--color-focus-ring)',
        accent: 'var(--color-accent)',
        'accent-foreground': 'var(--color-accent-foreground)',
        'accent-subtle': 'var(--color-accent-subtle)',
        primary: {
          DEFAULT: 'var(--color-primary-500)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          foreground: 'var(--color-primary-foreground)',
        },
        background: {
          DEFAULT: 'var(--color-background)',
          elevated: 'var(--color-background-elevated)',
          overlay: 'var(--color-background-overlay)',
        },
        success: 'var(--color-success)',
        'success-foreground': 'var(--color-success-foreground)',
        'success-subtle': 'var(--color-success-subtle)',
        warning: 'var(--color-warning)',
        'warning-foreground': 'var(--color-warning-foreground)',
        'warning-subtle': 'var(--color-warning-subtle)',
        error: 'var(--color-error)',
        'error-foreground': 'var(--color-error-foreground)',
        'error-subtle': 'var(--color-error-subtle)',
        info: 'var(--color-info)',
        'info-foreground': 'var(--color-info-foreground)',
        'info-subtle': 'var(--color-info-subtle)',
        neutral: {
          50: 'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          foreground: 'var(--color-neutral-foreground)',
        },
        /* Legacy aliases */
        navy: 'var(--color-accent)',
        orange: 'var(--color-highlight)',
        'orange-hover': 'var(--color-highlight-hover)',
        yellow: 'var(--color-yellow)',
        green: 'var(--color-accent)',
        'green-dark': 'var(--color-accent-active)',
        'green-fairway': '#1a5c1a',
        'green-putting': '#2d8a2d',
        'green-mid': '#3cb371',
        'green-light': '#5cb85c',
        'green-lime': '#7cb87c',
        'green-pale': '#90c890',
        'green-mint': '#b8e0b8',
        lightBlue: 'var(--wave-surface-alt)',
        pink: '#F2C4CE',
        peach: '#E8A87C',
        cream: 'var(--color-bg)',
        white: 'var(--color-surface-raised)',
        borderGray: 'var(--color-border)',
        placeholderGray: 'var(--color-text-muted)',
        textBody: 'var(--color-text-secondary)',
        muted: 'var(--color-text-muted)',
      },
      fontFamily: {
        display: ['var(--font-playfair)', 'Playfair Display', 'Georgia', 'serif'],
        script: ['var(--font-dancing)', 'Dancing Script', 'cursive'],
        body: ['var(--font-dm-sans)', 'DM Sans', 'system-ui', 'sans-serif'],
        outfit: ['var(--font-outfit)', 'Outfit', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        xs: 'var(--text-sm)',
        sm: 'var(--text-base)',
        base: 'var(--text-base)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
        hero: 'clamp(2.5rem, 2rem + 3vw, 5rem)',
        /* Section headings — used by section-title and components */
        h1: ['var(--text-3xl)', { lineHeight: '1.2', letterSpacing: '-0.02em' }],
        h2: ['var(--text-2xl)', { lineHeight: '1.3' }],
        h3: ['var(--text-xl)', { lineHeight: '1.35' }],
      },
      lineHeight: {
        tight: '1.05',
        snug: '1.2',
        normal: '1.5',
        relaxed: '1.65',
        loose: '1.75',
      },
      letterSpacing: {
        tighter: '-0.5px',
        wide: '0.08em',
        wider: '0.1em',
        widest: '0.15em',
      },
      maxWidth: {
        content: '1200px',
      },
      spacing: {
        'nav-height': '72px',
        'section': '96px',
        'section-lg': '128px',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '1': 'var(--shadow-1)',
        '2': 'var(--shadow-2)',
        '3': 'var(--shadow-3)',
        '4': 'var(--shadow-4)',
        '5': 'var(--shadow-5)',
        '1-primary': 'var(--shadow-1-primary)',
        '2-primary': 'var(--shadow-2-primary)',
        '3-primary': 'var(--shadow-3-primary)',
        '4-primary': 'var(--shadow-4-primary)',
        '5-primary': 'var(--shadow-5-primary)',
        card: 'var(--shadow-2-primary)',
        cardHover: 'var(--shadow-4-primary)',
        product: 'var(--shadow-3)',
        hero: 'var(--shadow-5-primary)',
        button: 'var(--shadow-3-primary)',
        elevation: 'var(--shadow-md)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
      transitionTimingFunction: {
        'ease-spring': 'var(--ease-spring)',
        'ease-bounce': 'var(--ease-bounce)',
      },
    },
  },
  plugins: [],
};

export default config;
